name: Build & Inject Kernel into Ubuntu 22.04.2 Raspberry Pi Image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  Download:
    runs-on: arc-runner-set
    permissions: write-all
    steps:
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y \
            wget xz-utils curl

      - name: Download Ubuntu 22.04.2 Raspberry Pi image
        run: |
          wget -O ubuntu-22.04.2-raspi.img.xz \
            https://cdimage.ubuntu.com/releases/24.04.2/release/ubuntu-24.04.2-preinstalled-server-arm64+raspi.img.xz
          unxz ubuntu-22.04.2-raspi.img.xz

      - name: Upload Raspberry Pi image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-raspi-image
          path: ubuntu-22.04.2-raspi.img

  Build:
    runs-on: arc-runner-set
    needs: Download
    permissions: write-all
    steps:
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y \
            qemu-user-static binfmt-support \
            kpartx mount unzip bc bison flex libssl-dev \
            make gcc-aarch64-linux-gnu u-boot-tools device-tree-compiler \
            rsync util-linux wget xz-utils git libguestfs-tools qemu-utils openssl curl

      - name: Clone Linux Kernel v6.6.y & Compile
        run: |
          git clone --depth=1 --branch rpi-6.6.y https://github.com/raspberrypi/linux.git
          cd linux
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make bcm2711_defconfig
          make -j$(nproc) Image modules dtbs

      - name: Install Kernel Modules
        run: |
          cd linux
          sudo make modules_install

      - name: Prepare kernel artifacts for upload
        id: kernel_info
        run: |
          cd linux
          KERNEL_VERSION=$(make -s kernelversion)
          cd ..
          mkdir -p kernel-artifacts
          cp linux/arch/arm64/boot/Image kernel-artifacts/vmlinuz-${KERNEL_VERSION}
          cp linux/arch/arm64/boot/dts/broadcom/bcm2712*.dtb kernel-artifacts/
          if [ -d linux/arch/arm64/boot/dts/overlays ]; then
            cp -r linux/arch/arm64/boot/dts/overlays kernel-artifacts/
          fi
          echo "kernel_version=$KERNEL_VERSION" >> $GITHUB_OUTPUT

      - name: Upload kernel build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: kernel-artifacts/

  Inject:
    runs-on: arc-runner-set
    needs: Build
    permissions: write-all
    steps:
      - name: Download Ubuntu Raspberry Pi image artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-raspi-image
          path: ./image

      - name: Download kernel build artifacts
        uses: actions/download-artifact@v4
        with:
          name: kernel-artifacts
          path: ./kernel-build-output

      - name: Install mtools and fdisk
        run: sudo apt-get update && sudo apt-get install -y mtools fdisk

      - name: Get boot partition start sector and size
        id: partition_info
        run: |
          PART_INFO=$(fdisk -l ./image/ubuntu-22.04.2-raspi.img | grep "^./image/ubuntu-22.04.2-raspi.img1")
          if [ -z "$PART_INFO" ]; then
            PART_INFO=$(fdisk -l ./image/ubuntu-22.04.2-raspi.img | grep " 1 ")
          fi
          echo "Partition info: $PART_INFO"
          START_SECTOR=$(echo $PART_INFO | awk '{print $4}')
          SECTORS=$(echo $PART_INFO | awk '{print $6}')
          echo "start_sector=$START_SECTOR" >> $GITHUB_OUTPUT
          echo "sectors=$SECTORS" >> $GITHUB_OUTPUT

      - name: Get root partition start sector and size
        id: partition_info_two
        run: |
          PART_INFO=$(fdisk -l ./image/ubuntu-22.04.2-raspi.img | grep "^./image/ubuntu-22.04.2-raspi.img2")
          if [ -z "$PART_INFO" ]; then
            PART_INFO=$(fdisk -l ./image/ubuntu-22.04.2-raspi.img | grep " 2 ")
          fi
          echo "Partition info: $PART_INFO"
          START_SECTOR=$(echo $PART_INFO | awk '{print $4}')
          SECTORS=$(echo $PART_INFO | awk '{print $6}')
          echo "start_sector=$START_SECTOR" >> $GITHUB_OUTPUT
          echo "sectors=$SECTORS" >> $GITHUB_OUTPUT

      - name: Extract boot partition image
        run: |
          dd if=./image/ubuntu-22.04.2-raspi.img of=boot-partition.img bs=512 skip=${{ steps.partition_info.outputs.start_sector }} count=${{ steps.partition_info.outputs.sectors }}

      - name: Configure mtools to access boot partition image
        run: |
          echo "drive p: file=\"$(pwd)/boot-partition.img\" partition=0" > ~/.mtoolsrc

      - name: Copy custom kernel files to boot partition image
        run: |
          mcopy -i boot-partition.img ./kernel-build-output/vmlinuz-${{ steps.kernel_info.outputs.kernel_version }} p:/
          # Optionally, copy initrd if exists:
          if [ -f ./kernel-build-output/initrd.img-${{ steps.kernel_info.outputs.kernel_version }} ]; then
            mcopy -i boot-partition.img ./kernel-build-output/initrd.img-${{ steps.kernel_info.outputs.kernel_version }} p:/
          fi

      - name: Update config.txt in boot partition
        run: |
          mcopy -i boot-partition.img p:/config.txt .
          grep -q '^kernel=vmlinuz-${{ steps.kernel_info.outputs.kernel_version }}$' config.txt || echo "kernel=vmlinuz-${{ steps.kernel_info.outputs.kernel_version }}" >> config.txt
          mcopy -o -i boot-partition.img config.txt p:/

      - name: Inject patched boot partition back into main image
        run: |
          dd if=boot-partition.img of=./image/ubuntu-22.04.2-raspi.img bs=512 seek=${{ steps.partition_info.outputs.start_sector }} count=${{ steps.partition_info.outputs.sectors }} conv=notrunc

      - name: Upload patched Raspberry Pi image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-rpi-patched.img
          path: ./image/ubuntu-22.04.2-raspi-${{ steps.kernel_info.outputs.kernel_version }}.img
